name:                yesod-static-remote
version:             0.0.0.1
github:              "NorfairKing/yesod-static-remote"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2019-2022 Tom Sydney Kerckhove"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- yesod-static

library:
  source-dirs: src
  dependencies:
    - bytestring
    - directory
    - filepath
    - http-client
    - http-client-tls
    - template-haskell
